---
# This playbook deploys a full web-server stack on the target machine
- name: Common tasks
  hosts: all
  remote_user: m_tachefini
  roles:
    - web
  tasks:
    command: /bin/bash /web/www/post-receive/post-receive.sh
    become: yes
    become_method: su
    become_user: nginx