---
- name: MySQL
  hosts: mtek_web
  remote_user: m_tachefini
  tasks:
          - name: Install MySQL
            become: yes
            dnf:
                    name: mysql-server
                    state: latest
          - name: Start server
