- name: Install wget
  become: yes
  dnf:
          name: wget
          state: latest

- name: Add the javascript script as a daemon
  become: yes
  copy:
          src: "{{node_service}}"
          dest: "/etc/systemd/system/gitpull.service"
          owner: root
          group: root
          mode: '0660'


- name: Download NodeJS
  get_url: 
      url: https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz
      dest: .
- name: Extract NodeJS
  unarchive:
          dest: .
          src:  node-v12.16.1-linux-x64.tar.xz
          remote_src: yes
- name: Verify if node is installed
  stat:
    path: /usr/bin/node
    register: result
- name: Copy node files
  become: yes
  shell: cp node-v12.16.1-linux-x64/* /usr -r
- name: Enable the node service
  become: yes
  systemd:
          enabled: yes
          force: yes
          daemon-reload: yes
          name: "{{node_service}}"
          state: started