---
- name: Common tasks for all hosts (Update)
  import_tasks: update.yml
- name: Setup webserver (Nginx)
  import_tasks: web.yml
- name: Install Node.js
  import_tasks: install_node.yml
- name: Synchronize with github 
  import_tasks: github_synchronize.yml