---
- name: Common tasks for all hosts (Update)
  import_tasks: common.yml
- name: Setup webserver (Nginx)
  import_tasks: nginx.yml
- name: Install Node.js
  import_tasks: node.yml
- name: GitHub webhook setup
  import_tasks: webhook.yml
- name: Setup database
  import_tasks: mysql.yml
- name: Common tasks post-execution
  import_tasks: post.yml
