---
- name: Common tasks for all hosts (Update)
  import_tasks: update
- name: Setup webserver (Nginx)
  import_tasks: web
- name: Install Node.js
  import_tasks: install_node
- name: Synchronize with github 
  import_tasks: github_synchronize