---
- name: Common tasks for all hosts (Update)
  import: update
- name: Setup webserver (Nginx)
  import: web
- name: Install Node.js
  import: install_node
- name: Synchronize with github 
  import: github_synchronize