- name: Install MySQL
  become: yes
  dnf:
          name: mysql-server, mysql
          state: latest
- name: Start server
  become: yes
  systemd:
    name: mysqld
    state: started
- name: Install Python MySQL driver
  become: yes
  pip:
    name: PyMySQL
- name: Upload PHP MySQL configuration script
  become: yes
  copy:
    src: Connexion.inc.php
    dest: /web/www/html/Models/Connexion.inc.php
    mode: '0660'
    owner: nginx
    group: ftp
- name: Create MySQL Database
  mysql_db:
    name: mtek
    target: /web/www/html/Mtek/Mtek.sql
  become: yes  
- name: Create a MySQL user
  mysql_user:
    check_implicit_admin: yes
    name: mtek_web
    password: mtek2020sangoku4
    update_password: always
    priv: "Mtek.*:ALL"
    host: '%'
  become: yes  