- name: Install MySQL
  become: yes
  dnf:
    name: mysql-server, mysql
    state: latest
- name: Copy MySQL configuration file
  become: yes
  copy:
    src: "mysql-server.cnf"
    dest: /etc/my.cnf.d/mysql-server.cnf
- name: Start server
  become: yes
  systemd:
    enabled: yes
    name: mysqld
    state: started
- name: Install Python MySQL driver
  become: yes
  pip:
    name: PyMySQL
- name: Upload PHP MySQL configuration script
  become: yes
  copy:
    src: Connexion.inc.php
    dest: /web/www/html/Connexion.inc.php
    mode: "0660"
    owner: nginx
    group: nginx
- name: Edit MySQL DB name in Connexion.inc.php
  become: yes
  replace:
    path: /web/www/html/Connexion.inc.php
    regexp: "{mysql_db}"
    replace: "{{mysql_db}}"
- name: Edit MySQL user name in Connexion.inc.php
  become: yes
  replace:
    path: /web/www/html/Connexion.inc.php
    regexp: "{mysql_user}"
    replace: "{{mysql_user}}"
- name: Edit MySQL password in Connexion.inc.php
  become: yes
  replace:
    path: /web/www/html/Connexion.inc.php
    regexp: "{mysql_password}"
    replace: "{{mysql_password}}"

- name: Copy MySQL script
  become: yes
  copy:
    src: "MySQL.sql"
    dest: /web/www/MySQL.sql
    mode: "0660"
    owner: nginx
    group: nginx
- name: Create MySQL Database
  mysql_db:
    name: all
    target: /web/www/MySQL.sql
    state: import
  become: yes
- name: Create a MySQL user
  mysql_user:
    check_implicit_admin: yes
    name: "{{mysql_user}}"
    password: "{{mysql_password}}"
    update_password: always
    priv: "{{mysql_db}}.*:ALL"
    host: "%"
  become: yes
