- name: Install nginx, PHP and PHP modules
  become: yes
  dnf:
    name: nginx, php-fpm, php-pdo, php-json, php-mysqlnd
    state: latest
    update_cache: yes

- name: Upload nginx configuration
  become: yes
  copy:
    src: "nginx.conf"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: Upload PHP configuration
  become: yes
  copy:
    src: php.ini
    dest: /etc/php.ini
    owner: root
    group: root
    mode: "0644"

- name: Upload PHP-FPM configuration
  become: yes
  copy:
    src: "www.conf"
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: "0644"

- name: Setup html directory
  become: yes
  file:
    path: /web/www/html/Models
    state: directory
    mode: "0760"
    owner: nginx
    group: nginx

- name: Enable nginx server
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted
