- name: Add yarn repositories
  become: yes
  shell: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
- name: Add Nodesource repositories
  become: yes
  shell: curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash -
- name: Install yarn
  become: yes
  dnf:
    name: nodejs, yarn
    state: latest
