- name: Install git
  become: yes
  dnf:
    name: git
    state: latest

- name: Upload scripts
  become: yes
  copy:
    src: post-receive
    dest: /web/www/
    owner: nginx
    group: nginx
    mode: "0760"

- name: Install webhook's dependencies
  become: yes
  become_user: nginx
  shell:
    chdir: /web/www/post-receive
    cmd: yarn add winston

- name: Create logs folder
  file:
    mode: "0700"
    group: nginx
    owner: nginx
    path: /var/log/webhook
    state: directory

- name: Add the javascript script as a daemon
  become: yes
  copy:
    src: webhook.service
    dest: /etc/systemd/system/webhook.service
    owner: root
    group: root
    mode: "0600"

- name: Copy front secret
  become: yes
  replace:
    path: /etc/systemd/system/webhook.service
    regexp: "{{front}}"
    replace: "{{front_secret}}"

- name: Copy back secret
  become: yes
  replace:
    path: /etc/systemd/system/webhook.service
    regexp: "{{back}}"
    replace: "{{back_secret}}"

- name: Enable nginx server
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted

- name: Create .ssh folder for nginx
  become: yes
  file:
    path: /var/lib/nginx/.ssh
    state: directory
    mode: "0760"
    owner: nginx
    group: nginx
- name: Setup git SSH key
  become: yes
  copy:
    src: "secrets/id_rsa"
    dest: /var/lib/nginx/.ssh/id_rsa
    owner: nginx
    group: nginx
    mode: "0760"
- name: Clone git repository for the server
  become: yes
  git:
    accept_hostkey: yes
    dest: /web/www/Models
    force: yes
    key_file: /var/lib/nginx/.ssh/id_rsa
    remote: origin
    repo: "{{github_back_url}}"
    umask: "0007"
- name: Clone git repository for the client
  become: yes
  git:
    accept_hostkey: yes
    dest: /web/www/Mtek
    force: yes
    key_file: /var/lib/nginx/.ssh/id_rsa
    remote: origin
    repo: "{{github_front_url}}"
    umask: "0007"
