github_front_url: git@github.com:younabobo/delivery.git
github_back_url: git@github.com:e-lies/MtekModels.git
front_secret: "{{lookup('file', 'secrets/front.secret')}}"
back_secret: "{{lookup('file', 'secrets/server.secret')}}"
mysql_user: delivery
mysql_db: delivery
website_name: delivery
domain_name: 167.86.107.200
